backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "blog"
    label: "Lectures"
    folder: "src/lectures"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "TitleBar", name: "titleBar", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }