backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "assets/blog"
collections:
  - name: "blog"
    label: "Lectures"
    folder: "src/lectures"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title", name: "title", widget: "string"
      - label: "Author", name: "author", widget: "string"
      - label: "Date", name: "date", widget: "datetime"
      - label: "Tags", name: "tags", widget: "list", default: ["post"]
      - label: "Body", name: "body", widget: "markdown"